# Generated by Django 2.2.24 on 2021-11-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.TextField(default='')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('qualis', models.TextField(default='')),
                ('area', models.TextField(default='')),
                ('local', models.TextField(default='')),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='horarios_laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.TextField(default='')),
                ('hora_entrada', models.DateTimeField(default='')),
                ('hora_saida', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField()),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('curso', models.TextField(default='')),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('funcao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='StatusArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico_Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idt', models.TextField()),
                ('nome', models.TextField()),
                ('telefone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(default='', unique=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True, unique=True)),
                ('email', models.TextField()),
                ('data_nascimento', models.TextField(max_length=20)),
                ('status', models.TextField()),
                ('funcao', models.TextField(default='')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, null=True)),
                ('titulo', models.TextField()),
                ('corpo', models.TextField()),
                ('data_lancamento_noticia', models.DateTimeField(null=True)),
                ('imagem', models.ImageField(upload_to='media')),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('coautor', models.TextField(default='')),
                ('orientador', models.TextField(default='')),
                ('autor', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.Professor')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.StatusArtigo')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('senha', models.TextField(default='')),
                ('matricula', models.TextField(default='')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cpf', models.IntegerField(null=True)),
                ('curso', models.TextField(default='')),
                ('data_nascimento', models.TextField(max_length=20)),
                ('eventos_cadastrado', models.ManyToManyField(to='sistemaReclamacoes.Evento')),
            ],
        ),
    ]
