# Generated by Django 2.2.24 on 2021-11-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0002_auto_20211109_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='matricula',
            new_name='idUser',
        ),
    ]
