# Generated by Django 2.2.24 on 2021-11-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0003_auto_20211109_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='atendente',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='situacaoAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tecnico_campo',
            name='idt',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idUser',
            field=models.TextField(default='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.TextField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemaReclamacoes.Cliente')),
            ],
        ),
    ]
