# Generated by Django 2.2.24 on 2021-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0004_auto_20211109_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='reclamacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemaEnfrentado', models.TextField()),
                ('comentarioProblema', models.TextField()),
            ],
        ),
    ]
