# Generated by Django 2.2.24 on 2021-12-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0005_reclamacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idUser',
        ),
        migrations.AddField(
            model_name='atendente',
            name='cpf',
            field=models.TextField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='data_nascimento',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='endereco',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='sexo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='telefone',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
