# Generated by Django 2.2.24 on 2021-12-07 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0006_auto_20211207_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='telefone',
        ),
    ]
