# Generated by Django 2.2.24 on 2021-12-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0007_auto_20211207_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='cpf',
            field=models.TextField(default='1', verbose_name=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='data_nascimento',
            field=models.TextField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='email',
            field=models.TextField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='endereco',
            field=models.TextField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='sexo',
            field=models.TextField(default='1', null=True),
        ),
        migrations.AddField(
            model_name='atendente',
            name='telefone',
            field=models.TextField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='nome',
            field=models.TextField(default='1'),
        ),
    ]
