# Generated by Django 2.2.24 on 2021-12-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0009_auto_20211207_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atendimento',
        ),
    ]
