# Generated by Django 2.2.24 on 2021-12-08 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0010_delete_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.TextField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaReclamacoes.Cliente')),
            ],
        ),
    ]
