# Generated by Django 2.2.24 on 2021-12-08 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0013_auto_20211207_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
