# Generated by Django 2.2.24 on 2021-12-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0014_auto_20211207_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atendimento',
        ),
    ]
