# Generated by Django 2.2.24 on 2021-12-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0015_delete_atendimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='situacaoAtendimento',
        ),
    ]
