# Generated by Django 2.2.24 on 2021-12-08 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0018_auto_20211207_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='situacaoAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='idUser',
            field=models.TextField(default='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='nome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.TextField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemaReclamacoes.Cliente')),
            ],
        ),
    ]
