# Generated by Django 2.2.24 on 2021-12-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaReclamacoes', '0019_auto_20211207_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistemaReclamacoes.Cliente'),
        ),
    ]
