# Generated by Django 2.2.24 on 2021-12-08 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistemaReclamacoes', '0021_auto_20211207_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='cliente',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cliente',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
